### ISSUE TITLE
Cool, but there are some problems

### ISSUE THREAD

**Issue by roife** [jojojames/gud-lldb#1]
When I try to use "gud-watch", I got the message "gud-watch is a no-op in this mode".
How to use it properly?
I'm using Emacs 25.2

**Comment by jojojames** [comment]
It might be educational to look at the source and see if you can add that functionality. :)

I might take a look at what gud-watch does and implement it myself once I have some time.

There were other things I wanted to add to this like toggling breakpoints, etc.

It's far from finished.
